[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.3"

[dev]
  comand = "hugo server --buildDrafts --disableFastRender"
  targetPort = 1313

[context.branch-deploy]
  command = "hugo server --buildDrafts --disableFastRender"