local_backend: true

backend:
  name: git-gateway
  branch: master
media_folder: /static/images
public_folder: /images
publish_mode: editorial_workflow
collections:
  - name: docs
    label: Documents
    label_singular: 'Document'
    folder: content/docs
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Draft
        name: draft
        widget: boolean
      - label: Body
        name: body
        widget: markdown
    meta: { 
      path: { widget: string, label: 'Path', index_file: '_index'}
      }