backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: images/upload
public_folder: /img
collections:
  - name: 'docs'
    label: 'Documentation'
    folder: 'content/docs'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog'
    label: 'Blog Posts'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }